### ISSUE TITLE
Windows install script only works with GNAT Community 2018 edition.

### ISSUE THREAD

**Issue by guinguin-instruments** [AdaCore/gnat_community_install_script#6]
The install script provided only works with the latest version (2018) of the ADA GNAT Community windows installer. With previous version the installer does not react to 'gui' actions.

Is there a way to silently install previous version on windows ?

**Comment by setton** [comment]
Hello! Yes the installers for the previous versions can be scripted too, use `/S  /D=<target_dir>`. For instance:

   `gnat-gpl-2017-x86-windows-bin.exe /S /D=C:\old_gnat\`

**Comment by CosminH** [comment]
Hi, 
How about gnat-community-2019-20190517-x86_64-windows-bin.exe? It doesn't accept anything :((. 
I am trying to deploy via SCCM.
BR!

**Comment by reznikmm** [comment]
@CosminH if you have [choco](https://chocolatey.org/packages/gnat-gpl/2019.0) installed you can setup GNAT with just one command:
```
choco install gnat-gpl 
```
otherwise do as [README.md](https://github.com/AdaCore/gnat_community_install_script) suggests:
```
install_package.bat <path_to_package> <target_dir>
```

**Comment by eine** [comment]
@reznikmm what about macOS? I am trying to install gnat-community-2019-20190517-x86_64-darwin-bin (http://mirrors.cdn.adacore.com/art/5ce0322c31e87a8f1d4253fa) in a Travis CI job with no success.

I could extract the DMG with 7z, and then execute the binary inside:

``` bash
curl -o dmgfile http://mirrors.cdn.adacore.com/art/5ce0322c31e87a8f1d4253fa
7z x dmgfile
installer="gnat-community-2019-20190517-x86_64-darwin-bin/gnat-community-2019-20190517-x86_64-darwin-bin.app/Contents/MacOS/gnat-community-2019-20190517-x86_64-darwin-bin"

mkdir -p gnat
chmod +x $installer
./$installer PREFIX=gnat

PATH=$PWD/gnat/bin:$PATH
```

gnatmake, etc. seem to work, but the linker fails: https://travis-ci.org/1138-4EB/ghdl/builds/557262854#L700

I then tried with the scripts in this repo, but `install_script.qs` seems to be outdated and the installation does not finish.

Any hint?
